# Generated by Django 5.1.1 on 2024-09-27 19:55

import aviso.views
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(verbose_name=aviso.views.check_url)),
                ('name', models.TextField()),
                ('location', models.CharField(max_length=200)),
            ],
        ),
    ]
